version: 2
project_name: nodey

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    binary: nodey

archives:
  - # this name template makes the archive name compatible with the standard brew formula naming
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  -
    # GOAL: Installs to `dhirajnikam/homebrew-tap`
    repository:
      owner: dhirajnikam
      name: homebrew-tap
      token: "{{ .Env.GITHUB_TOKEN }}"

    name: nodey
    homepage: "https://github.com/dhirajnikam/nodey"
    description: "AI-Powered Flowchart Architect for your Terminal"
    license: "MIT"
    
    # dependencies:
    #   - name: git
    
    install: |
      bin.install "nodey"
